import { useMemo, useState } from 'react';
import {
  Modal,
  Card,
  Button,
  Toggle,
  Heading,
  Paragraph,
  Badge,
  Tag,
  CodeBlock,
  useToast,
} from '../../components/common';
import { hexToRgb, rgbToHex, slugify, fmtHsl } from '../../lib/color';
import { wcagRatio, wcagBadge, bestTextOn } from '../../lib/contrast';

/* ------------------------------------------------------------------ *
 * Helpers
 * ------------------------------------------------------------------ */
function rgbStr(hex) {
  const { r, g, b } = hexToRgb(hex);
  return `rgb(${Math.round(r)}, ${Math.round(g)}, ${Math.round(b)})`;
}
function readableText(bgHex) {
  return bestTextOn(bgHex, ['#ffffff', '#0a0a0a']);
}

/* ------------------------------------------------------------------ *
 * Canvas exporter — manual paint of swatches + text
 * ------------------------------------------------------------------ */
function exportPng({ palette, name, baseHex, algorithm }) {
  const w = 1600;
  const rowH = 220;
  const headerH = 260;
  const footerH = 80;
  const n = palette.length || 1;
  const swatchW = (w - 80) / n;
  const h = headerH + rowH + footerH;
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d');

  // Background
  ctx.fillStyle = '#ffffff';
  ctx.fillRect(0, 0, w, h);

  // Header band
  ctx.fillStyle = baseHex;
  ctx.fillRect(0, 0, w, 8);

  // Title
  ctx.fillStyle = '#0a0a0a';
  ctx.font = '700 56px ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif';
  ctx.textAlign = 'left';
  ctx.textBaseline = 'top';
  ctx.fillText(name || 'Palette Spec', 40, 50);

  ctx.font = '500 28px ui-monospace, Menlo, monospace';
  ctx.fillStyle = '#525252';
  ctx.fillText(`Base ${(baseHex || '').toUpperCase()}  •  ${algorithm || 'Tailwind CSS'}`, 40, 130);

  ctx.font = '400 22px ui-sans-serif, system-ui, sans-serif';
  ctx.fillStyle = '#737373';
  ctx.fillText('shipit-palette.app — palette spec sheet', 40, 180);

  // Swatches row
  const yTop = headerH;
  palette.forEach((s, i) => {
    const x = 40 + i * swatchW;
    ctx.fillStyle = s.hex;
    ctx.fillRect(x, yTop, swatchW - 8, rowH - 20);

    const tc = readableText(s.hex);
    ctx.fillStyle = tc;
    ctx.font = '600 22px ui-sans-serif, system-ui, sans-serif';
    ctx.textAlign = 'left';
    ctx.fillText(String(s.label || ''), x + 16, yTop + 16);
    ctx.font = '500 18px ui-monospace, Menlo, monospace';
    ctx.fillText(s.hex.toUpperCase(), x + 16, yTop + rowH - 60);
  });

  // Footer
  ctx.fillStyle = '#a3a3a3';
  ctx.font = '400 20px ui-sans-serif, system-ui, sans-serif';
  ctx.textAlign = 'right';
  ctx.fillText(`Generated by ShipIt Palette · ${n} shades`, w - 40, h - 50);

  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${slugify(name || 'palette')}-spec.png`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }, 'image/png');
}

/* ------------------------------------------------------------------ *
 * Sub-components
 * ------------------------------------------------------------------ */
function SwatchCard({ shade }) {
  const text = readableText(shade.hex);
  return (
    <div className="flex flex-col rounded-xl overflow-hidden border border-neutral-200 dark:border-neutral-800 bg-white dark:bg-neutral-900">
      <div
        className="flex h-24 items-end p-3"
        style={{ background: shade.hex, color: text }}
      >
        <span className="text-sm font-semibold">{shade.label}</span>
      </div>
      <div className="px-3 py-2.5 text-[11px] font-mono text-neutral-700 dark:text-neutral-300 leading-5">
        <div>{shade.hex.toUpperCase()}</div>
        <div className="text-neutral-500">{rgbStr(shade.hex)}</div>
        <div className="text-neutral-500">{fmtHsl(hexToRgb(shade.hex))}</div>
      </div>
    </div>
  );
}

function ContrastTable({ palette }) {
  const samples = palette.length >= 6
    ? [palette[1], palette[Math.floor(palette.length / 2)], palette[palette.length - 2]]
    : palette.slice(0, 3);
  return (
    <div className="grid gap-2 sm:grid-cols-3">
      {samples.map((s) => {
        const onWhite = wcagRatio(s.hex, '#ffffff');
        const onBlack = wcagRatio(s.hex, '#000000');
        const wb = wcagBadge(onWhite);
        const bb = wcagBadge(onBlack);
        return (
          <div key={s.label} className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-3">
            <div className="flex items-center gap-2">
              <span className="h-5 w-5 rounded" style={{ background: s.hex }} />
              <span className="text-sm font-semibold">{s.label}</span>
              <span className="ml-auto text-[11px] font-mono text-neutral-500">
                {s.hex.toUpperCase()}
              </span>
            </div>
            <div className="mt-2 flex flex-wrap gap-1.5 text-[11px]">
              <Tag>vs #FFF · {onWhite.toFixed(2)} <span style={{ color: wb.color }}>{wb.tag}</span></Tag>
              <Tag>vs #000 · {onBlack.toFixed(2)} <span style={{ color: bb.color }}>{bb.tag}</span></Tag>
            </div>
          </div>
        );
      })}
    </div>
  );
}

/* ------------------------------------------------------------------ *
 * Modal
 * ------------------------------------------------------------------ */
export default function SpecSheetModal({
  open,
  onClose,
  palette = [],
  name = 'My Palette',
  baseHex = '#3b82f6',
  algorithm = 'Tailwind CSS',
}) {
  const { toast } = useToast();
  const [includeCode, setIncludeCode] = useState(true);
  const [includeA11y, setIncludeA11y] = useState(true);

  const cssSnippet = useMemo(() => {
    const slug = slugify(name || 'brand');
    const lines = [':root {'];
    palette.forEach((s) => lines.push(`  --${slug}-${s.label}: ${s.hex};`));
    lines.push('}');
    return lines.join('\n');
  }, [palette, name]);

  const mid = palette[Math.floor(palette.length / 2)] || { hex: baseHex, label: 'base' };
  const light = palette[1] || { hex: baseHex, label: 'tint' };
  const dark = palette[palette.length - 2] || { hex: baseHex, label: 'shade' };

  const onPrint = () => {
    toast('Opening print dialog…');
    setTimeout(() => window.print(), 100);
  };

  return (
    <Modal open={open} onClose={onClose} size="full" title="Spec Sheet">
      <style>{`
        @media print {
          body * { visibility: hidden; }
          .spec-print, .spec-print * { visibility: visible; }
          .spec-print { position: absolute; left: 0; top: 0; width: 100%; }
          .spec-no-print { display: none !important; }
        }
      `}</style>

      {/* Toolbar */}
      <div className="spec-no-print mb-4 flex flex-wrap items-center gap-3">
        <Toggle checked={includeCode} onChange={setIncludeCode} label="Include code samples" />
        <Toggle checked={includeA11y} onChange={setIncludeA11y} label="Include accessibility notes" />
        <div className="ml-auto flex flex-wrap gap-2">
          <Button
            variant="brand"
            onClick={() => exportPng({ palette, name, baseHex, algorithm })}
          >
            Download as PNG
          </Button>
          <Button variant="outline" onClick={onPrint}>
            Print to PDF
          </Button>
        </div>
      </div>

      {/* Spec sheet */}
      <div className="spec-print flex flex-col gap-5">
        <Card accent>
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div>
              <Heading as="h2" accent>{name}</Heading>
              <Paragraph size="sm" className="mt-1">
                Generated using <strong>{algorithm}</strong> · {palette.length} shades · base{' '}
                <span className="font-mono">{(baseHex || '').toUpperCase()}</span>
              </Paragraph>
            </div>
            <Badge variant="brand">Spec Sheet</Badge>
          </div>
          <div className="mt-4 flex h-3 w-full overflow-hidden rounded-full">
            {palette.map((s) => (
              <div key={s.label} className="flex-1" style={{ background: s.hex }} />
            ))}
          </div>
        </Card>

        <Card padded>
          <Heading as="h4">Swatches</Heading>
          <Paragraph size="sm" className="mt-1">
            Hex, RGB and HSL values for every shade in the palette.
          </Paragraph>
          <div
            className="mt-4 grid gap-3"
            style={{ gridTemplateColumns: `repeat(${Math.min(palette.length, 6)}, minmax(0, 1fr))` }}
          >
            {palette.map((s) => <SwatchCard key={s.label} shade={s} />)}
          </div>
        </Card>

        <Card padded>
          <Heading as="h4">Usage examples</Heading>
          <div className="mt-4 grid gap-4 md:grid-cols-3">
            <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-4">
              <div className="text-xs uppercase tracking-wide text-neutral-500 mb-2">Button</div>
              <button className="rounded-lg px-4 py-2 text-sm font-semibold shadow" style={{ background: mid.hex, color: readableText(mid.hex) }}>Get started</button>
            </div>
            <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-4">
              <div className="text-xs uppercase tracking-wide text-neutral-500 mb-2">Card</div>
              <div className="rounded-lg p-3" style={{ background: light.hex, color: readableText(light.hex) }}>
                <div className="text-sm font-semibold">Heading</div>
                <div className="text-xs opacity-80">Subtle subtext goes here.</div>
              </div>
            </div>
            <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-4">
              <div className="text-xs uppercase tracking-wide text-neutral-500 mb-2">Text</div>
              <p className="text-sm" style={{ color: dark.hex }}>The quick brown fox jumps over the lazy dog.</p>
              <p className="text-xs mt-1" style={{ color: mid.hex }}>Secondary tone for less emphasis.</p>
            </div>
          </div>
        </Card>

        {includeA11y && (
          <Card padded>
            <Heading as="h4">WCAG contrast</Heading>
            <Paragraph size="sm" className="mt-1">
              Quick contrast check of representative shades vs pure white and black backgrounds.
            </Paragraph>
            <div className="mt-3">
              <ContrastTable palette={palette} />
            </div>
          </Card>
        )}

        {includeCode && (
          <Card padded>
            <Heading as="h4">CSS variables</Heading>
            <Paragraph size="sm" className="mt-1">
              Drop into your stylesheet to use the palette across your app.
            </Paragraph>
            <div className="mt-3">
              <CodeBlock code={cssSnippet} lang="css" />
            </div>
          </Card>
        )}
      </div>
    </Modal>
  );
}
